name: test CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cd
      run: cd bin
    - name: test
      run: ./lwivm $GITHUB_WORKSPACE/test/test
